 apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: order-events
  labels:
    app: order-system
spec:
  partitions: 5
  replicas: 2
  config:
    retention.ms: 604800000  # 7 дней
    cleanup.policy: compact

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inventory-compensation
  labels:
    app: inventory-system
spec:
  partitions: 3
  replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inventory-dlq
  labels:
    app: inventory-system
spec:
  partitions: 1
  replicas: 2